apiVersion: "app.redislabs.com/v1alpha1"
kind: "RedisEnterpriseCluster"
metadata:
  name: "redis-enterprise-cluster"
spec:
  nodes: 3
  #  persistentSpec:
  #    enabled: true
  #    storageClassName: "gp2"
  uiServiceType: LoadBalancer
  serviceBrokerSpec:
    enabled: true
    persistentSpec:
      storageClassName: "gp2"
  username: "damon@redislabs.com"
  redisEnterpriseNodeResources:
    limits:
      cpu: 4
      memory: 16Gi
    requests:
      cpu: 4
      memory: 16Gi
  redisEnterpriseImageSpec:
    imagePullPolicy:  IfNotPresent
    Repository:       redislabs/redis
    versionTag:       5.2.0-14

