apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-servers
spec:
  replicas: 1 
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: redis-benchmark
    spec:
      #nodeSelector:
      #cloud.google.com/gke-nodepool: default-pool
      containers:
      - name: benchmark
        image: redislabs/memtier_benchmark
        args: ["-d", "10", "-n", "20000000", "--pipeline=2", "-a", "$(REDIS_PASSWORD)", "-s", "$(REDIS_SERVER)", "-p", "$(REDIS_PORT)"]
        resources:
          limits:
            cpu: "0.5"
            memory: "250Mi"
          requests:
            cpu: "0.25"
            memory: "128Mi"
        env:
         - name: REDIS_PORT
           value: "10098"   # redis port
         - name: REDIS_SERVER
           value: "redis-45614856-7755-11e9-98f8-0a580a800035"  # can be full hostname or just the resource name in k8s
#         - name: REDIS_PASSWORD
#           value: "ddd"
